### ISSUE TITLE
获取 machineID 时可能会溢出

### ISSUE THREAD

**Issue by godruoyi** [polaris1119/snowflake#1]
如当 IP 地址为 10.3.255.100 时：

```go
func machineID() (uint8, uint8) {
    ...
    return ip[2], ip[3]
}
```

这里返回的 datacenterID 和 workerID 都超过 31（最大长度为 5 位，最大值为 2(111111) => 10(31)）。Twitter 的雪花算法我也遇到过这个问题，https://github.com/godruoyi/go-snowflake/blob/master/privateip.go#L60。

可以试着采用 sony 的雪花算法实现 https://github.com/sony/sonyflake。

**Comment by polaris1119** [comment]
做了掩码处理
